version: "3.9"
services:
  rabbitmq:
    image: masstransit/rabbitmq:latest
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - my-network

  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:8.0.0-preview.6
    container_name: aspire-dashboard
    ports:
      - 18888:18888
      - 4317:18889
    networks:
      - my-network
      
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Th3_P@ssw0rd-421
    ports:
      - "1433:1433"
    networks:
      - my-network
      
  redis:
    image: redis:latest
    command: /bin/sh -c "redis-server --requirepass Th3_P@ssw0rd-421"
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - my-network
      
  # my-app:
    # image: my-app
    # container_name: my-app
    # build:
      # context: .
      # dockerfile: ...
    # environment:
      # # - DOTNET__DASHBOARD__UNSECURED__ALLOW__ANONYMOUS=true;
      # # - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true;
      # # - OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4317;
    # ports:
      # - 808:8080
    # networks:
      # - my-network
      
volumes:
  rabbitmq_data:
  redis_data:
  
networks:
  my-network: